---
title: "Midterm"
author: "Brendan Cullen"
date: "4/30/2019"
output: 
  html_document:
      toc: yes
      toc_depth: 3
      toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE}
library(tidyverse)
library(purrr)
library(glue)
library(rio)
library(janitor)
library(colorblindr)
library(here)
library(glue)
```

# Part A: Data

```{r}
# define function to download data  
download_file <- function(year) {
    link <- glue::glue("https://www.oregon.gov/ode/educator-resources/assessment/TestResults20{year}/pagr_schools_ela_raceethnicity_{year-1}{year}.xlsx")
    rio::import(link, setclass = "tibble", na = c("-", "--", "*"))
}
```

## Question 1

```{r cache=TRUE}
# download all the data from the past 4 years
data <- map_df(15:18, download_file) 

# wrangle data
data <- data %>% 
  clean_names() %>% 
  filter(student_group %in% c("White", "Hispanic/Latino")) %>% 
  gather(c(number_level_1, number_level_2, number_level_3, number_level_4), key = level, value = n) %>%
  mutate(level = recode(level, 
                        "number_level_1" = 1, 
                        "number_level_2" = 2, 
                        "number_level_3" = 3, 
                        "number_level_4" = 4)) %>% 
  select(academic_year, district, school, student_group, grade_level, level, n) %>% 
  drop_na(n)

data
```

## Question 2

```{r}
#  Calculate the cumulative n for each school by student group, grade, and academic year.
data_cn <- split(data, list(data$school, 
                            data$academic_year, 
                            data$student_group, 
                            data$grade_level), drop = TRUE) %>% 
          map_df(~mutate(.x, cn = cumsum(n)))

data_cn
```

## Question 3

```{r}
# Reformat the data 
data_cn <- data_cn %>% 
  select(-n) %>% 
  spread(student_group, cn) %>% 
  clean_names() %>% 
  drop_na(c(hispanic_latino, white))

data_cn
```

# Part B: Achievement gaps

```{r}
# define funtion for later use
gap <- function(data, ref, foc) {
    x <- data[[ref]]
    y <- data[[foc]]
    auc <- pracma::trapz(y / y[length(x)],
                         x / x[length(x)])
    sqrt(2)*qnorm(auc)
}
```

## Question 1

```{r}
# Estimate an achievement gap effect size for every school in the state that reported data on both student groups (i.e., using the data we created above), for each grade level in each academic year.
data_es <- data_cn %>% 
  group_by(school, district, grade_level, academic_year) %>%
  nest() %>% 
  mutate(es = map_dbl(data, ~gap(.x, ref = "white", foc = "hispanic_latino")))
```

## Question 2

```{r eval=FALSE}
# Reproduce example plot

# Wrangle data for plot
plot_data <- data_es %>% 
  mutate(grade_level = as.factor(recode(grade_level, 
                        "Grade 3" = 3, 
                        "Grade 4" = 4,
                        "Grade 5" = 5,
                        "Grade 6" = 6,
                        "Grade 7" = 7,
                        "Grade 8" = 8,
                        "Grade HS (11)" = 11)),
         district = map_chr(district, ~str_replace(.x, "SD.*", "School District"))) %>% 
  filter(school == "Ashland Middle School", academic_year == "2017-2018")

# Reproduce example plot 
plot_data %>%
  ggplot(aes(grade_level, es, fill = es)) +
  geom_col(alpha = 0.7) + 
  coord_flip() + 
  labs(x = "Grade", 
       y = "Effect Size", 
       title = ("Achievement Gap Estimates: Ashland Middle School"),
       subtitle = "Students coded as White as compared to those coded as Hispanic/Latino", 
       caption = paste("2017-2017 School year", "Ashland School Disrict", "Oregon", sep = ", ")) +
  geom_hline(yintercept = 0, size = 1.5, color = "#92D5CA", alpha = 0.8) + 
  scale_fill_viridis_c(limits = c(-1.5, 1.5)) + 
  theme_minimal(base_size = 14) +
  theme(legend.position = c(.7,-.2),
        legend.direction = "horizontal",
        legend.title = element_blank(),
        legend.key.width = unit(3, "cm"),
        legend.text = element_text(vjust = -.5),
        plot.margin = unit(c(rep(1.75, 4)), "cm"),
        panel.grid.minor = element_blank(),
        plot.caption = element_text(vjust = -1))
```


```{r}
# write function to create plots 
plot_function <- function(data, school, district, academic_year) {
  ggplot(data, aes(grade_level, es, fill = es)) +
  geom_col(alpha = 0.7) + 
  coord_flip() + 
  labs(x = "Grade", 
       y = "Effect Size", 
       title = glue::glue("Achievement Gap Estimates: {school}"), 
       subtitle = "Students coded as White as compared to those coded as Hispanic/Latino", 
       caption = glue::glue("{academic_year} School year, {district}, Oregon")) +
  geom_hline(yintercept = 0, size = 1.5, color = "#92D5CA", alpha = 0.8) + 
  scale_fill_viridis_c(limits = c(-1.5, 1.5)) + 
  theme_minimal(base_size = 14) +
  theme(legend.position = c(.7,-.2),
        legend.direction = "horizontal",
        legend.title = element_blank(),
        legend.key.width = unit(3, "cm"),
        legend.text = element_text(vjust = -.5),
        plot.margin = unit(c(rep(1.75, 4)), "cm"),
        panel.grid.minor = element_blank(),
        plot.caption = element_text(vjust = -1))
}

# wrangle data and create plots
plot_data <- data_es %>% 
  mutate(grade_level = as.factor(recode(grade_level, 
                        "Grade 3" = 3, 
                        "Grade 4" = 4,
                        "Grade 5" = 5,
                        "Grade 6" = 6,
                        "Grade 7" = 7,
                        "Grade 8" = 8,
                        "Grade HS (11)" = 11)),
         district = map_chr(district, ~str_replace(.x, "SD.*", "School District"))) %>% 
  select(-data) %>% 
  group_by(school, district, academic_year) %>% 
  nest() %>% 
  slice(1:100) %>% 
  mutate(plot = pmap(list(data, school, district, academic_year), plot_function))
```

## Question 3

```{r warning=FALSE}
# Save the plots into a “plots” directory. Make sure the file names are meaningful.

# create directory for plots
dir.create(here::here("plots"))

# create filenames
plot_data <- plot_data %>% 
         mutate(filename = as.character(glue::glue(here::here("plots"), "/{school}_{academic_year}.png")))

# save files
walk2(plot_data$filename, plot_data$plot, ggsave,
      width = 10, 
      height = 8)
```

